# Generated by Django 5.2.17 on 2026-09-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='número de cuenta')),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('status', models.CharField(choices=[('active', 'activa'), ('frozen', 'congelada'), ('closed', 'cerrada')], default='active', max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'banking_account',
            },
        ),
    ]
