# Generated by Django 5.2.17 on 2026-10-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[("savings", "ahorros"), ("checking", "corriente")],
                db_column="tipo",
                default="savings",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                db_column="saldo", decimal_places=2, default=0, max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(db_column="moneda", default="PEN", max_length=3),
        ),
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.CharField(
                db_column="numero",
                max_length=20,
                unique=True,
                verbose_name="número de cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="opened_at",
            field=models.DateTimeField(auto_now_add=True, db_column="fecha_apertura"),
        ),
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "activa"),
                    ("frozen", "congelada"),
                    ("closed", "cerrada"),
                ],
                db_column="estado",
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="account",
            table="cuenta",
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_code",
                    models.CharField(
                        db_column="codigo_operacion",
                        max_length=20,
                        unique=True,
                        verbose_name="código de operación",
                    ),
                ),
                (
                    "destination_number",
                    models.CharField(
                        db_column="numero_destino",
                        max_length=20,
                        verbose_name="cuenta o CCI destino",
                    ),
                ),
                (
                    "destination_holder",
                    models.CharField(
                        blank=True,
                        db_column="titular_destino",
                        default="",
                        max_length=150,
                    ),
                ),
                (
                    "destination_bank",
                    models.CharField(
                        db_column="banco_destino", default="Luma Bank", max_length=80
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="monto", decimal_places=2, max_digits=14
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        db_column="comision",
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="comisión",
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="moneda", default="PEN", max_length=3),
                ),
                (
                    "concept",
                    models.CharField(
                        blank=True, db_column="concepto", default="", max_length=140
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pendiente"),
                            ("completed", "completada"),
                            ("failed", "fallida"),
                            ("reversed", "revertida"),
                        ],
                        db_column="estado",
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, db_column="fecha_completada", null=True
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        db_column="cuenta_destino_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_received",
                        to="banking.account",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        db_column="cuenta_origen_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_sent",
                        to="banking.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "transferencia",
                "verbose_name_plural": "transferencias",
                "db_table": "transferencia",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "abono"), ("debit", "cargo")],
                        db_column="sentido",
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "depósito"),
                            ("withdrawal", "retiro"),
                            ("transfer", "transferencia"),
                            ("card_purchase", "consumo con tarjeta"),
                            ("loan_disbursement", "desembolso de préstamo"),
                            ("loan_payment", "pago de cuota"),
                            ("fee", "comisión"),
                            ("interest", "interés"),
                            ("reversal", "extorno"),
                        ],
                        db_column="tipo",
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="monto", decimal_places=2, max_digits=14
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        db_column="saldo_resultante",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="saldo resultante",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="descripcion", default="", max_length=140
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="cuenta_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="banking.account",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        db_column="transferencia_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="banking.transfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento",
                "verbose_name_plural": "movimientos",
                "db_table": "movimiento",
            },
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(db_column="alias", max_length=60)),
                (
                    "holder_name",
                    models.CharField(
                        db_column="nombre_titular",
                        max_length=150,
                        verbose_name="titular",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        db_column="numero_cuenta",
                        max_length=20,
                        verbose_name="cuenta o CCI destino",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        db_column="banco", default="Luma Bank", max_length=80
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "beneficiario",
                "verbose_name_plural": "beneficiarios",
                "db_table": "beneficiario",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "account_number"),
                        name="beneficiario_usuario_cuenta_unico",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["source_account", "created_at"],
                name="transferenc_cuenta__3e271a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="transferencia_monto_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee__gte", 0)), name="transferencia_comision_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_account", models.F("destination_account")), _negated=True
                ),
                name="transferencia_cuentas_distintas",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "created_at"], name="movimiento_cuenta__eb246e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="movimiento_monto_gt_0"
            ),
        ),
    ]
