# Generated by Django 5.2.17 on 2026-10-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banking", "0002_modelo_completo_es"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        db_column="monto_solicitado",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="monto solicitado",
                    ),
                ),
                (
                    "annual_rate",
                    models.DecimalField(
                        db_column="tasa_anual",
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="TEA (%)",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveSmallIntegerField(
                        db_column="plazo_meses", verbose_name="plazo en meses"
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        db_column="cuota_mensual",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="cuota mensual",
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        db_column="saldo_pendiente",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="saldo pendiente",
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="moneda", default="PEN", max_length=3),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        db_column="motivo",
                        default="",
                        max_length=140,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "solicitado"),
                            ("approved", "aprobado"),
                            ("rejected", "rechazado"),
                            ("disbursed", "desembolsado"),
                            ("paid", "pagado"),
                            ("defaulted", "en mora"),
                        ],
                        db_column="estado",
                        default="requested",
                        max_length=16,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="fecha_solicitud"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, db_column="fecha_decision", null=True
                    ),
                ),
                (
                    "disbursed_at",
                    models.DateTimeField(
                        blank=True, db_column="fecha_desembolso", null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="cuenta_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="banking.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "préstamo",
                "verbose_name_plural": "préstamos",
                "db_table": "prestamo",
            },
        ),
        migrations.CreateModel(
            name="LoanInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        db_column="numero", verbose_name="número de cuota"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        db_column="fecha_vencimiento",
                        verbose_name="fecha de vencimiento",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        db_column="amortizacion",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="amortización",
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        db_column="interes",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="interés",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        db_column="total",
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="total de la cuota",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pendiente"),
                            ("paid", "pagada"),
                            ("overdue", "vencida"),
                        ],
                        db_column="estado",
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, db_column="fecha_pago", null=True),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        db_column="prestamo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="loans.loan",
                    ),
                ),
                (
                    "payment_transaction",
                    models.OneToOneField(
                        blank=True,
                        db_column="movimiento_pago_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_installment",
                        to="banking.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuota",
                "verbose_name_plural": "cuotas",
                "db_table": "cuota_prestamo",
                "ordering": ["loan", "number"],
            },
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("principal__gt", 0)), name="prestamo_monto_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("annual_rate__gte", 0)),
                name="prestamo_tasa_anual_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("term_months__gte", 1)),
                name="prestamo_plazo_meses_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("outstanding_balance__gte", 0)),
                name="prestamo_saldo_pendiente_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="loaninstallment",
            constraint=models.UniqueConstraint(
                fields=("loan", "number"), name="cuota_prestamo_prestamo_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="loaninstallment",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gt", 0)),
                name="cuota_prestamo_total_gt_0",
            ),
        ),
    ]
