# Generated by Django 5.2.17 on 2026-09-07 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False, verbose_name='identidad verificada (RENIEC)'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (8 dígitos).', max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.CreateModel(
            name='DniValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=16)),
                ('mode', models.CharField(choices=[('production', 'production'), ('mock', 'mock')], max_length=16)),
                ('result', models.CharField(choices=[('found', 'encontrado'), ('not_found', 'no encontrado'), ('invalid', 'DNI inválido'), ('error', 'error del servicio'), ('cached', 'desde caché')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_dni_validation_log',
                'indexes': [models.Index(fields=['dni', 'created_at'], name='accounts_dn_dni_fc048c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=128)),
                ('object_key', models.CharField(max_length=256)),
                ('algorithm', models.CharField(help_text="Modelo/versión que generó el vector, p. ej. 'face-api ssdMobilenetv1 128d'.", max_length=128)),
                ('dimensions', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'embedding facial',
                'verbose_name_plural': 'embeddings faciales',
                'db_table': 'accounts_face_embedding',
            },
        ),
    ]
