# Generated by Django 5.2.17 on 2026-09-07 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hu02_registro_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_facial_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='email o DNI ingresado', max_length=254)),
                ('method', models.CharField(choices=[('facial', 'reconocimiento facial'), ('password_totp', 'contraseña + TOTP')], max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'éxito'), ('bad_face', 'rostro no coincide'), ('bad_liveness', 'prueba de vida fallida (sospechoso)'), ('bad_password', 'contraseña incorrecta'), ('bad_totp', 'código TOTP incorrecto'), ('locked', 'cuenta bloqueada'), ('unknown_user', 'usuario no encontrado')], max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_login_attempt',
                'indexes': [models.Index(fields=['identifier', 'created_at'], name='accounts_lo_identif_9286aa_idx')],
            },
        ),
    ]
