# Generated by Django 5.2.17 on 2026-10-05 20:09

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_hu03_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_column="accion",
                        help_text="p. ej. 'transfer.create', 'card.block'",
                        max_length=64,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        blank=True, db_column="entidad", default="", max_length=64
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, db_column="entidad_id", default="", max_length=64
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, db_column="direccion_ip", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, db_column="metadatos", default=dict),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="fecha_creacion", default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "bitacora_auditoria",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("security", "seguridad"),
                            ("transfer", "transferencia"),
                            ("card", "tarjeta"),
                            ("loan", "préstamo"),
                            ("system", "sistema"),
                        ],
                        db_column="tipo",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(db_column="titulo", max_length=120)),
                (
                    "body",
                    models.CharField(
                        blank=True, db_column="mensaje", default="", max_length=500
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, db_column="fecha_lectura", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="fecha_creacion", default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "notificacion",
            },
        ),
        migrations.RenameIndex(
            model_name="dnivalidationlog",
            new_name="registro_va_dni_446a73_idx",
            old_name="accounts_dn_dni_fc048c_idx",
        ),
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="intento_log_identif_6de9c7_idx",
            old_name="accounts_lo_identif_9286aa_idx",
        ),
        migrations.AlterField(
            model_name="dnivalidationlog",
            name="created_at",
            field=models.DateTimeField(
                db_column="fecha_creacion", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="dnivalidationlog",
            name="dni",
            field=models.CharField(db_column="dni", max_length=16),
        ),
        migrations.AlterField(
            model_name="dnivalidationlog",
            name="mode",
            field=models.CharField(
                choices=[("production", "production"), ("mock", "mock")],
                db_column="modo",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="dnivalidationlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("found", "encontrado"),
                    ("not_found", "no encontrado"),
                    ("invalid", "DNI inválido"),
                    ("error", "error del servicio"),
                    ("cached", "desde caché"),
                ],
                db_column="resultado",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="algorithm",
            field=models.CharField(
                db_column="algoritmo",
                help_text="Modelo/versión que generó el vector, p. ej. 'face-api ssdMobilenetv1 128d'.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="bucket",
            field=models.CharField(db_column="bucket", max_length=128),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="dimensions",
            field=models.PositiveIntegerField(db_column="dimensiones"),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="object_key",
            field=models.CharField(db_column="clave_objeto", max_length=256),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_column="fecha_actualizacion"),
        ),
        migrations.AlterField(
            model_name="faceembedding",
            name="user",
            field=models.OneToOneField(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_embedding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="created_at",
            field=models.DateTimeField(
                db_column="fecha_creacion", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="identifier",
            field=models.CharField(
                db_column="identificador",
                help_text="email o DNI ingresado",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, db_column="direccion_ip", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="method",
            field=models.CharField(
                choices=[
                    ("facial", "reconocimiento facial"),
                    ("password_totp", "contraseña + TOTP"),
                ],
                db_column="metodo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "éxito"),
                    ("bad_face", "rostro no coincide"),
                    ("bad_liveness", "prueba de vida fallida (sospechoso)"),
                    ("bad_password", "contraseña incorrecta"),
                    ("bad_totp", "código TOTP incorrecto"),
                    ("locked", "cuenta bloqueada"),
                    ("unknown_user", "usuario no encontrado"),
                ],
                db_column="resultado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="suspicious",
            field=models.BooleanField(db_column="sospechoso", default=False),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="user_agent",
            field=models.CharField(
                blank=True, db_column="agente_usuario", default="", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                db_column="fecha_nacimiento",
                null=True,
                verbose_name="fecha de nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                db_column="fecha_registro",
                default=django.utils.timezone.now,
                verbose_name="fecha de registro",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=models.CharField(
                blank=True,
                db_column="dni",
                help_text="Documento Nacional de Identidad (8 dígitos).",
                max_length=8,
                null=True,
                unique=True,
                verbose_name="DNI",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_column="correo",
                max_length=254,
                unique=True,
                verbose_name="correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_facial_attempts",
            field=models.PositiveSmallIntegerField(
                db_column="intentos_faciales_fallidos", default=0
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                db_column="intentos_login_fallidos", default=0
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, db_column="nombres", max_length=150, verbose_name="nombres"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                db_column="esta_activo", default=True, verbose_name="activo"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_identity_verified",
            field=models.BooleanField(
                db_column="identidad_verificada",
                default=False,
                verbose_name="identidad verificada (RENIEC)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                db_column="es_personal", default=False, verbose_name="es personal"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                db_column="es_superusuario",
                default=False,
                verbose_name="es superusuario",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True,
                db_column="ultimo_acceso",
                null=True,
                verbose_name="último acceso",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                db_column="apellidos",
                max_length=150,
                verbose_name="apellidos",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, db_column="bloqueado_hasta", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                db_column="clave", max_length=128, verbose_name="contraseña"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="totp_secret_encrypted",
            field=models.CharField(
                blank=True, db_column="secreto_totp_cifrado", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_column="nombre_usuario",
                error_messages={"unique": "Ya existe un usuario con ese nombre."},
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="nombre de usuario",
            ),
        ),
        migrations.AlterModelTable(
            name="dnivalidationlog",
            table="registro_validacion_dni",
        ),
        migrations.AlterModelTable(
            name="faceembedding",
            table="embedding_facial",
        ),
        migrations.AlterModelTable(
            name="loginattempt",
            table="intento_login",
        ),
        migrations.AlterModelTable(
            name="user",
            table="usuario",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"], name="bitacora_au_usuario_5f178c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["entity", "entity_id"], name="bitacora_au_entidad_a7b7f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificacio_usuario_dc3d02_idx"
            ),
        ),
    ]
