# Generated by Django 5.2.17 on 2026-10-05 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hu03_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='descriptor_fingerprint',
            field=models.CharField(blank=True, editable=False, help_text='HMAC-SHA256 del descriptor; detecta replay de una captura ajena.', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LivenessAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('registro', 'registro / apertura de cuenta'), ('login', 'inicio de sesión facial')], max_length=16)),
                ('challenge_id', models.CharField(max_length=64, unique=True)),
                ('plan', models.JSONField(help_text='Reto sorteado por el servidor.')),
                ('completed_actions', models.JSONField(help_text='Gestos ejecutados, en orden.')),
                ('duration_ms', models.PositiveIntegerField(help_text='Tiempo entre emisión y respuesta.')),
                ('descriptor_algorithm', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_attestations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atestación de vida',
                'verbose_name_plural': 'atestaciones de vida',
                'db_table': 'accounts_liveness_attestation',
                'ordering': ['-created_at'],
            },
        ),
    ]
