# Generated by Django 5.2.17 on 2026-10-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banking", "0002_modelo_completo_es"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("debit", "débito"), ("credit", "crédito")],
                        db_column="tipo",
                        max_length=8,
                    ),
                ),
                (
                    "brand",
                    models.CharField(db_column="marca", default="Visa", max_length=20),
                ),
                (
                    "token",
                    models.CharField(
                        db_column="token",
                        max_length=64,
                        unique=True,
                        verbose_name="token de la tarjeta",
                    ),
                ),
                (
                    "last4",
                    models.CharField(
                        db_column="ultimos4",
                        max_length=4,
                        verbose_name="últimos 4 dígitos",
                    ),
                ),
                (
                    "holder_name",
                    models.CharField(db_column="nombre_titular", max_length=150),
                ),
                (
                    "expiry_month",
                    models.PositiveSmallIntegerField(db_column="mes_vencimiento"),
                ),
                (
                    "expiry_year",
                    models.PositiveSmallIntegerField(db_column="anio_vencimiento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "activa"),
                            ("blocked", "bloqueada"),
                            ("expired", "vencida"),
                            ("cancelled", "cancelada"),
                        ],
                        db_column="estado",
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        db_column="linea_credito",
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(
                        db_column="limite_diario",
                        decimal_places=2,
                        default=2000,
                        max_digits=14,
                    ),
                ),
                (
                    "online_purchases_enabled",
                    models.BooleanField(
                        db_column="compras_internet_habilitadas", default=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_column="cuenta_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="banking.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tarjeta",
                "verbose_name_plural": "tarjetas",
                "db_table": "tarjeta",
            },
        ),
        migrations.CreateModel(
            name="CardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant",
                    models.CharField(
                        db_column="comercio", max_length=120, verbose_name="comercio"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="monto", decimal_places=2, max_digits=14
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="moneda", default="PEN", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("authorized", "autorizada"),
                            ("settled", "liquidada"),
                            ("declined", "rechazada"),
                            ("reversed", "revertida"),
                        ],
                        db_column="estado",
                        default="authorized",
                        max_length=16,
                    ),
                ),
                (
                    "authorization_code",
                    models.CharField(
                        blank=True,
                        db_column="codigo_autorizacion",
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "account_transaction",
                    models.OneToOneField(
                        blank=True,
                        db_column="movimiento_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_transaction",
                        to="banking.transaction",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        db_column="tarjeta_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "verbose_name": "consumo con tarjeta",
                "verbose_name_plural": "consumos con tarjeta",
                "db_table": "consumo_tarjeta",
            },
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(("expiry_month__gte", 1), ("expiry_month__lte", 12)),
                name="tarjeta_mes_vencimiento_1_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_limit__gte", 0)),
                name="tarjeta_limite_diario_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="cardtransaction",
            index=models.Index(
                fields=["card", "created_at"], name="consumo_tar_tarjeta_ad3e3e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cardtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="consumo_tarjeta_monto_gt_0"
            ),
        ),
    ]
